spr_0
	.sprite "      ##      ##        "
	.sprite "  # #   ##  ##  # #     "
	.sprite "  # # #  #   ## # #     "
	.sprite "  # # #  #   ## # #     "
	.sprite "  # # #  # # ## # #     "
	.sprite "  ### # # ### # # #     "
	.sprite "    ### # ### # ##      "
	.sprite "    ##### ### ####      "
	.sprite "    ##  ######  ##      "
	.sprite "    ##  ######  ##      "
	.sprite "        ######          "
	.sprite "        ######          "
	.sprite "      ##########        "
	.sprite "    ##  ######  ##      "
	.sprite "    ##  ######  ##      "
	.sprite "    ##    ##    ##      "
	.sprite "  ####          ##      "
	.sprite "                ####    "

	.sprite "        ##  ##          "
	.sprite "        ##    ##        "
	.sprite "          ##  ##        "
	.sprite "      # #  #   ## #     "
	.sprite "    # # #  # # ## # #   "
	.sprite "    # # #  ### ## # #   "
	.sprite "    # ### # ### # # #   "
	.sprite "    # ##### ### ###     "
	.sprite "    ##    ######    ##  "
	.sprite "      ##  ######    ##  "
	.sprite "        ########  ##    "
	.sprite "          ########      "
	.sprite "        ##########      "
	.sprite "      ##  ######  ##    "
	.sprite "      ##  ######  ##    "
	.sprite "      ##    ##    ##    "
	.sprite "      ##          ####  "
	.sprite "    ####                "

	.sprite "     #       #          "
	.sprite "        #        #      "
	.sprite "     #      #  #   #    "
	.sprite "   #  ##    #           "
	.sprite "       ##  ###          "
	.sprite "     #  ## ###   ###    "
	.sprite "         ########       "
	.sprite "      #####  ####   #   "
	.sprite "   #######    ####      "
	.sprite "       ####   ######    "
	.sprite "    #  ####  ###  ###   "
	.sprite "      ## #######        "
	.sprite "   #  #   ###  ##   #   "
	.sprite "     #    ##  #  #      "
	.sprite "          #       #     "
	.sprite "       #  #             "
	.sprite "              #         "
	.sprite "        #               "

	.sprite "                        "
	.sprite "          #             "
	.sprite "        #     #         "
	.sprite "     #     #      #     "
	.sprite "               #        "
	.sprite "       #  #       #     "
	.sprite "   #       ###          "
	.sprite "      #  #####  #       "
	.sprite "    #    ######   #     "
	.sprite "       #  #### #        "
	.sprite "          ####      #   "
	.sprite "    #   #  ## #         "
	.sprite "           #      #     "
	.sprite "             #          "
	.sprite "       #         #      "
	.sprite "                        "
	.sprite "             #          "
	.sprite "                        "

	.sprite "            #           "
	.sprite "            #           "
	.sprite "           ###          "
	.sprite "           ###          "
	.sprite "   #        #           "
	.sprite "   #        #           "
	.sprite "   ###      #           "
	.sprite "   ####     #    #      "
	.sprite "     ###  #  #   # #    "
	.sprite "      #####  ##  #  #   "
	.sprite "       ####  #####  #   "
	.sprite "   #   #### #  ######   "
	.sprite "   # ####### # ######   "
	.sprite "   ######  #####  ##    "
	.sprite "   ###    ###  ##       "
	.sprite "          #######       "
	.sprite "              ##        "
	.sprite "                        "

	.sprite "            #           "
	.sprite "            #           "
	.sprite "           ###          "
	.sprite "           ###          "
	.sprite "            #           "
	.sprite "            #           "
	.sprite "            #           "
	.sprite "            #    #      "
	.sprite "   #      #  #   # #    "
	.sprite "   #     ##  ##  #  #   "
	.sprite "   ########  #####  #   "
	.sprite "   ######## #  ######   "
	.sprite "         ### # ######   "
	.sprite "           #####  ##    "
	.sprite "          ###  ##       "
	.sprite "          #######       "
	.sprite "              ##        "
	.sprite "                        "

	.sprite "            #           "
	.sprite "            #           "
	.sprite "           ###          "
	.sprite "           ###          "
	.sprite "            #           "
	.sprite "            #           "
	.sprite "            #           "
	.sprite "   #        #    #      "
	.sprite "   #      #  #   # #    "
	.sprite "   ####  ##  ##  #  #   "
	.sprite "   ########  #####  #   "
	.sprite "       #### #  ######   "
	.sprite "   #  ###### # ######   "
	.sprite "   # ####  #####  ##    "
	.sprite "   #####  ###  ##       "
	.sprite "   ###    #######       "
	.sprite "              ##        "
	.sprite "                        "

	.sprite "                #       "
	.sprite "                  #     "
	.sprite "            #       #   "
	.sprite "         #       #      "
	.sprite "       ##     ##        "
	.sprite "      ##       ##  #    "
	.sprite "      ##      # #       "
	.sprite "       ##     #         "
	.sprite "       ###    #         "
	.sprite "        ##   #          "
	.sprite "   #    ##   #          "
	.sprite "   #    ###  #   #      "
	.sprite "   #    ### #    # #    "
	.sprite "   ###  ### # # ##  #   "
	.sprite "   ######## # #######   "
	.sprite "    #######  # ######   "
	.sprite "      ####### ### ##    "
	.sprite "          ######        "



_ = (spr_0)

