	.sprite "              ###       "
	.sprite "             # ###      "
	.sprite "               ###  #   "
	.sprite "            #####       "
	.sprite "              ### ##    "
	.sprite "              #######   "
	.sprite "             ##  # ##   "
	.sprite "     ##     ###  # #    "
	.sprite "   # ## # # # #  ###    "
	.sprite "     ##   # # # ####    "
	.sprite "            ##### ##    "
	.sprite "             ####       "
	.sprite "              ####      "
	.sprite "              #####     "
	.sprite "             ## ###     "
	.sprite "             ##  ###    "
	.sprite "             ##   ##    "
	.sprite "           #### ####    "

	.sprite "              ###       "
	.sprite "             # ###      "
	.sprite "               ###  #   "
	.sprite "            #####       "
	.sprite "              ### ##    "
	.sprite "              #######   "
	.sprite "             ##  # ##   "
	.sprite "     ##     ###  # #    "
	.sprite "   # ## # # # #  ###    "
	.sprite "     ##   # # # ####    "
	.sprite "            ##### ##    "
	.sprite "             ####       "
	.sprite "              ##        "
	.sprite "              ##        "
	.sprite "              ##        "
	.sprite "              ##        "
	.sprite "              ##        "
	.sprite "            ####        "

	.sprite "              ###       "
	.sprite "             # ###      "
	.sprite "               ###  #   "
	.sprite "            #####       "
	.sprite "              ### ##    "
	.sprite "              #######   "
	.sprite "             ##  # ##   "
	.sprite "     ##     ###  # #    "
	.sprite "   # ## # # # #  ###    "
	.sprite "     ##   # # # ####    "
	.sprite "            ##### ##    "
	.sprite "             ####       "
	.sprite "             #####      "
	.sprite "            ######      "
	.sprite "           ###  ##      "
	.sprite "          ###   ###     "
	.sprite "          ##     ##     "
	.sprite "        ####   ####     "

	.sprite "     #          ###     "
	.sprite "        #      # ###    "
	.sprite "    #            ###    "
	.sprite "      #       #####     "
	.sprite "   #    ##      ####    "
	.sprite "       ##        ####   "
	.sprite "       #  #     ## ##   "
	.sprite "     #    # #  ## # #   "
	.sprite "            # # #  ##   "
	.sprite "              # # ###   "
	.sprite "              #######   "
	.sprite "      #    #########    "
	.sprite "       #  ##########    "
	.sprite "       #####     ###    "
	.sprite "        ##       ###    "
	.sprite "                ###     "
	.sprite "                ###     "
	.sprite "             #####      "
